# Site settings
title: thrownewexception();
email: kele_bru@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about scalable software, personal opinion on software design and remember... throw a new exception once in a while.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: BrunoElo
github_username:  BrunoMVPCosta

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
